### ISSUE TITLE
`spring_stream::handler::Handler<_>` not satisfied for stream listener fn

### ISSUE THREAD

**Issue by CM-IV** [spring-rs/spring-rs#118]
I am trying to test out the `spring_stream` feature but am running into an issue where the `Handler` trait is not implemented:

`rustc: 1.83.0`
`OS: Fedora Linux 41`

```
rustc: the trait bound `fn(spring_web::extractor::Json<Payload>) -> impl std::future::Future<Output = ()> {listen_topic_do_something}: spring_stream::handler::Handler<_>` is not satisfied
the trait `spring_stream::handler::Handler<_>` is not implemented for fn item `fn(spring_web::extractor::Json<Payload>) -> impl std::future::Future<Output = ()> {listen_topic_do_something}`

```
```toml
# app.toml
[web]
port = 8081              # Port number to bind
connect_info = false     # Whether to use client connection information, default false
graceful = true          # Whether to enable graceful shutdown, default false

[web.middlewares]
logger = { enable = true, level = "info" }

[logger]
enable = true            # Whether to enable the log function, which is enabled by default
pretty_backtrace = false # Whether to print stack information, which is disabled by default.
level = "info"           # The default log level is info
format = "pretty"       # The log format supports compact, pretty, and json.

[sqlx]
uri = "sqlite://db/sqlite.db?mode=rwc"

[stream]
uri = "file://./stream"

[stream.file]
connect = { create_file = "CreateIfNotExists" }

```

```toml
# Cargo.toml
[package]
name = "spring_rs_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
spring = "0.3.1"
spring-sqlx = { version = "0.3.0", features = ["sqlite"] }
spring-stream = { version = "0.3.0", features = ["json", "file"] }
spring-web = "0.3.0"
tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros"] }

[profile.release]
lto = "fat"
opt-level = "z"
debug = 0
overflow-checks = false
panic = "abort"
codegen-units = 1
```

```rs
// My Code example
use serde::{Deserialize, Serialize};
use serde_json::json;
use spring::{auto_config, tracing, App};
use spring_sqlx::SqlxPlugin;
use spring_stream::file::{AutoStreamReset, FileConsumerOptions};
use spring_stream::handler::TypedConsumer;
use spring_stream::{stream_listener, Consumers, Producer, StreamPlugin};
use spring_web::axum::Json;
use spring_web::error::Result;
use spring_web::extractor::Component;
use spring_web::get;
use spring_web::{axum::response::IntoResponse, WebConfigurator, WebPlugin};

#[derive(Debug, Serialize, Deserialize)]
pub struct Payload {
    success: bool,
    msg: String,
}

// Main function entry
#[auto_config(WebConfigurator)]
#[tokio::main]
async fn main() {
    App::new()
        .add_plugin(StreamPlugin)
        .add_plugin(SqlxPlugin)
        .add_plugin(WebPlugin)
        .add_consumer(consumers())
        .run()
        .await
}

#[get("/api/streamer")]
async fn hello_world(Component(producer): Component<Producer>) -> Result<impl IntoResponse> {
    let json = json!({
        "success": true,
        "msg": "This is a test"
    });

    let resp = producer
        .send_json("the_topic", json)
        .await
        .expect("Failed to send stream");

    let seq = resp.sequence();

    Ok(Json(json!({ "seq": seq })))
}

fn consumers() -> Consumers {
    Consumers::new().typed_consumer(listen_topic_do_something)
}

// Error Occurs Here v
#[stream_listener(
    "the_topic",
    file_consumer_options = fill_file_consumer_options
)]
async fn listen_topic_do_something(Json(payload): Json<Payload>) {
    tracing::info!("{:#?}", payload);
}
// Error Occurs Here ^

fn fill_file_consumer_options(opts: &mut FileConsumerOptions) {
    opts.set_auto_stream_reset(AutoStreamReset::Earliest);
}

```
