### ISSUE TITLE
Wildcard cors cant be assigned

### ISSUE THREAD

**Issue by KagChi** [spring-rs/spring-rs#97]
Add access logging

**Comment by holmofy** [comment]
spring-rs integrates common middleware of tower-http, [TraceLayer](https://docs.rs/tower-http/latest/tower_http/trace/index.html) is one of them, which provides functions similar to AccessLog
TraceLayer is not enabled by default, you can enable it with the following configuration

```toml
[web]
logger = { enable = true }
```

However, the default log level used by TraceLayer is `DEBUG`, and the default log level used by spring-rs is `INFO`. Therefore, AccessLog is not printed by default. You can enable `tower_http::trace` to output to the console by specifying its log filter level.

```toml
[logger]
override_filter = "info,tower_http::trace=debug"
```
